# Generated by Django 6.0 on 2026-02-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bandana', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='contact',
        ),
    ]
