# Generated by Django 6.0 on 2026-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bandana', '0002_rename_index_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pnumber',
            field=models.IntegerField(null=True),
        ),
    ]
